
// This file is automatically generated from the YAML data dictionary
export const data = {
  "classes": {
    "Scientific_Discipline": {
      "definition": "Information about the scientific discipline and research context.",
      "element_flag": true,
      "attributes": [
        "study_focus",
        "scientific_field",
        "investigation_technique"
      ],
      "nested_classes": {}
    },
    "Target_Object": {
      "definition": "Information about the target of observation, whether it is a celestial body, feature, or other object.",
      "element_flag": true,
      "attributes": [
        "object_name",
        "parent_body",
        "target_scope"
      ],
      "nested_classes": {
        "Object_Type": {
          "attributes": [
            "planet_type",
            "particles_and_fields_type",
            "dust_type",
            "solar_component_type",
            "solar_system_context",
            "exoplanet_type"
          ],
          "nested_classes": {
            "Small_Body": {
              "attributes": [
                "asteroid_type",
                "trans_neptunian_object_type",
                "centaur_type",
                "kuiper_belt_object_type",
                "oort_cloud_object_type",
                "comet_type",
                "satellite_type"
              ],
              "nested_classes": {}
            },
            "Atmosphere": {
              "attributes": [
                "atmospheric_layer",
                "atmosphere_study_type"
              ],
              "nested_classes": {}
            },
            "Rings": {
              "attributes": [
                "ring_type",
                "ring_division",
                "ring_feature"
              ],
              "nested_classes": {}
            }
          }
        },
        "Feature": {
          "attributes": [
            "feature_name",
            "feature_type"
          ],
          "nested_classes": {}
        },
        "Physical_Properties": {
          "attributes": [
            "material_type",
            "process_type",
            "composition_type"
          ],
          "nested_classes": {}
        },
        "Environmental_Context": {
          "attributes": [
            "temperature_regime",
            "pressure_conditions",
            "radiation_environment",
            "atmospheric_presence"
          ],
          "nested_classes": {}
        }
      }
    },
    "Data_Collection": {
      "definition": "Information about how the data was collected and its format.",
      "element_flag": true,
      "attributes": [
        "collection_method",
        "instrument_type",
        "data_category",
        "data_format"
      ],
      "nested_classes": {
        "Temporal_Epoch": {
          "attributes": [
            "earth_geologic_epoch",
            "moon_geologic_epoch",
            "mars_geologic_epoch",
            "vesta_geologic_epoch",
            "ceres_geologic_epoch"
          ],
          "nested_classes": {}
        }
      }
    },
    "Research_Context": {
      "definition": "Information about the research context and associated metadata.",
      "element_flag": true,
      "attributes": [
        "research_goals",
        "related_publications",
        "keywords",
        "principal_investigator",
        "institution"
      ],
      "nested_classes": {
        "Software_Used": {
          "attributes": [
            "data_visualization_software",
            "modeling_software",
            "orbital_mechanics_software",
            "digital_terrain_modeling_software",
            "other_software"
          ],
          "nested_classes": {}
        }
      }
    },
    "Object_Type": {
      "definition": "Select the categories within which the data would fit into",
      "element_flag": false,
      "attributes": [
        "planet_type",
        "particles_and_fields_type",
        "dust_type",
        "solar_component_type",
        "solar_system_context",
        "exoplanet_type"
      ],
      "nested_classes": {
        "Small_Body": {
          "attributes": [
            "asteroid_type",
            "trans_neptunian_object_type",
            "centaur_type",
            "kuiper_belt_object_type",
            "oort_cloud_object_type",
            "comet_type",
            "satellite_type"
          ],
          "nested_classes": {}
        },
        "Atmosphere": {
          "attributes": [
            "atmospheric_layer",
            "atmosphere_study_type"
          ],
          "nested_classes": {}
        },
        "Rings": {
          "attributes": [
            "ring_type",
            "ring_division",
            "ring_feature"
          ],
          "nested_classes": {}
        }
      }
    },
    "Small_Body": {
      "definition": "Small body",
      "element_flag": false,
      "attributes": [
        "asteroid_type",
        "trans_neptunian_object_type",
        "centaur_type",
        "kuiper_belt_object_type",
        "oort_cloud_object_type",
        "comet_type",
        "satellite_type"
      ],
      "nested_classes": {}
    },
    "Atmosphere": {
      "definition": "Atmosphere of a celestial body",
      "element_flag": false,
      "attributes": [
        "atmospheric_layer",
        "atmosphere_study_type"
      ],
      "nested_classes": {}
    },
    "Rings": {
      "definition": "Rings of an object",
      "element_flag": false,
      "attributes": [
        "ring_type",
        "ring_division",
        "ring_feature"
      ],
      "nested_classes": {}
    },
    "Feature": {
      "definition": "Feature",
      "element_flag": false,
      "attributes": [
        "feature_name",
        "feature_type"
      ],
      "nested_classes": {}
    },
    "Physical_Properties": {
      "definition": "Information about the physical properties of the object under study.",
      "element_flag": false,
      "attributes": [
        "material_type",
        "process_type",
        "composition_type"
      ],
      "nested_classes": {}
    },
    "Environmental_Context": {
      "definition": "Information about the environmental conditions at the study location.",
      "element_flag": false,
      "attributes": [
        "temperature_regime",
        "pressure_conditions",
        "radiation_environment",
        "atmospheric_presence"
      ],
      "nested_classes": {}
    },
    "Temporal_Epoch": {
      "definition": "The temporal epoch of the data collection.",
      "element_flag": false,
      "attributes": [
        "earth_geologic_epoch",
        "moon_geologic_epoch",
        "mars_geologic_epoch",
        "vesta_geologic_epoch",
        "ceres_geologic_epoch"
      ],
      "nested_classes": {}
    },
    "Software_Used": {
      "definition": "Software used to analyze the data.",
      "element_flag": false,
      "attributes": [
        "data_visualization_software",
        "modeling_software",
        "orbital_mechanics_software",
        "digital_terrain_modeling_software",
        "other_software"
      ],
      "nested_classes": {}
    }
  },
  "attributes": {
    "study_focus": {
      "definition": "High-level research focus.",
      "examples": {
        "Surface": "Study focused on planetary geology such as features or properties",
        "Interior": "Study focused on internal structure or processes",
        "Atmosphere": "Study focused on atmospheric properties or dynamics",
        "Magnetosphere": "Study focused on magnetic field properties or interactions",
        "Orbital_Dynamics": "Study focused on orbital properties or behaviors",
        "Composition": "Study focused on chemical or mineral composition",
        "Plasma": "Study of plasma and ionospheres",
        "Space Weather": "Study of the change in surfaces due to space weather effects",
        "Planetary Protection": "Study focused on planetary protection",
        "Rings": "Study focused on ring and ring-moon systems",
        "Resources": "In-situ resource characterization and utilization"
      }
    },
    "scientific_field": {
      "definition": "What are the different scientific fields of study.",
      "examples": {
        "Astrobiology": "Study of life in the universe",
        "Astronomy_Observation": "Observation of celestial objects",
        "Astronomy_Radar": "Radar observations of celestial objects",
        "Astronomy_Exoplanets": "Study of exoplanets",
        "Astronomy_Spectroscopy": "Spectroscopy of celestial objects",
        "Biology": "Study of life and living systems",
        "Chemistry": "Study of chemical composition, reactions, and properties",
        "Geology_Geophysics": "Geophysics of the Earth and other planets",
        "Geology_Seismology": "Seismology of the Earth and other planets",
        "Geology_Surface": "Surface studies of the Earth and other planets",
        "Geology_Crater_Counting": "Crater counting of the Earth and other planets",
        "Geology_Interior_Studies": "Interior studies of the Earth and other planets",
        "Dynamics": "Dynamics of the Earth and other planets",
        "Mathematics": "Mathematical analysis or methods",
        "Laboratory_Geochemistry": "Geochemistry of physical samples",
        "Laboratory_Cosmochemistry": "Cosmochemistry of physical samples",
        "Laboratory_Age_Dating": "Age dating of physical samples",
        "Laboratory_Analytic_Chemistry": "Analytic chemistry of physical samples",
        "Laboratory_Spectral_Analysis": "Spectral analysis of physical samples",
        "Atmospheric_Study": "Atmospheric studies of the Earth and other planets",
        "Impact": "Measuring and categorizing impact craters and rates",
        "Hydrology": "Fluvial mechanics",
        "Exoplanets": "Detection and characterizing exoplanets",
        "Modeling": "Modeling of the Earth and other planets",
        "Magnetospheres": "Magnetospheres of the Earth and other planets",
        "Physics": "Study of matter, energy, forces, and related physical processes",
        "Space_Physics": "Space physics of the Earth and other planets"
      }
    },
    "investigation_technique": {
      "definition": "What method of scientific investigations are used.",
      "examples": {
        "Spectroscopy": "Collection of spectra",
        "Modeling": "Computer-based simulation or modeling",
        "Mapping": "Collection of maps",
        "Radar": "Collection of radar data",
        "Seismology": "Collection of seismic data",
        "Ground based observation": "Data that was derived from Earth-based telescopes",
        "Gravimetry": "Collection of gravity data",
        "Remote Sensing": "Various data collected via remote sensing techniques",
        "LiDAR": "Light Detection and Ranging",
        "Geochemistry": "Collection of geochemical/cosmochemical data",
        "Laboratory": "Various laboratory work",
        "Data analysis": "General analysis of data",
        "Artificial Intelligence": "AI and machine learning techniques",
        "ICPMS": "Collection of inductively coupled plasma mass spectrometry data"
      }
    },
    "object_name": {
      "definition": "Name of the object"
    },
    "parent_body": {
      "definition": "Parent body of the object"
    },
    "target_scope": {
      "definition": "Scope of the data collection",
      "examples": {
        "Global": "Data collected from the entire object",
        "Regional": "Data collected from a large region of the object",
        "Local": "Data collected from a small location on the object"
      }
    },
    "asteroid_type": {
      "definition": "Asteroid",
      "examples": {
        "Near_Earth": "Asteroids with orbits that bring them close to Earth",
        "Trojan": "Asteroids that share an orbit with a planet",
        "Active": "Asteroids that show comet-like activity",
        "Main_Belt": "Asteroids in the main asteroid belt",
        "PHA": "Potential Hazardous Asteroid"
      }
    },
    "trans_neptunian_object_type": {
      "definition": "Trans-Neptunian Object",
      "examples": {
        "Classical": "Objects in the classical Kuiper belt",
        "Resonant": "Objects in orbital resonance with Neptune",
        "Scattered": "Objects scattered by Neptune",
        "Detached": "Objects with orbits not strongly influenced by Neptune"
      }
    },
    "centaur_type": {
      "definition": "Centaur",
      "examples": {
        "Active": "Centaurs showing comet-like activity",
        "Inactive": "Centaurs without comet-like activity"
      }
    },
    "kuiper_belt_object_type": {
      "definition": "Kuiper Belt Object",
      "examples": {
        "Classical": "Objects in the classical Kuiper belt",
        "Resonant": "Objects in orbital resonance with Neptune",
        "Scattered": "Objects scattered by Neptune"
      }
    },
    "oort_cloud_object_type": {
      "definition": "Oort Cloud Object",
      "examples": {
        "Inner": "Objects in the inner Oort cloud",
        "Outer": "Objects in the outer Oort cloud"
      }
    },
    "comet_type": {
      "definition": "Comet",
      "examples": {
        "Jupiter_Family": "Comets that orbit Jupiter",
        "Single_Pass": "Comets that pass through the inner solar system"
      }
    },
    "satellite_type": {
      "definition": "Satellite",
      "examples": {
        "Icy_Moons": "Icy moons of a planet",
        "Galilean_Moons": "Galilean moons of Jupiter",
        "Irregular_Moons": "Irregular moons of a planet",
        "Captured_Moons": "Captured moons of a planet",
        "Shepherding_Moon": "Shepherding moon of a planet"
      }
    },
    "planet_type": {
      "definition": "Planet",
      "examples": {
        "Gas_Giant": "Large planets composed mainly of gas",
        "Terrestrial": "Rocky planets similar to Earth",
        "Interior": "Planets closer to the Sun than Earth"
      }
    },
    "atmospheric_layer": {
      "definition": "Layer of the atmosphere",
      "examples": {
        "Troposphere": "Lowest layer of the atmosphere",
        "Stratosphere": "Layer above the troposphere",
        "Ionosphere": "Layer containing ions",
        "Exosphere": "Outermost layer of the atmosphere"
      }
    },
    "atmosphere_study_type": {
      "definition": "Type of study of the atmosphere",
      "examples": {
        "Temperature_Profile": "Temperature profile of the atmosphere",
        "Scale_Height": "Scale height of the atmosphere",
        "Density_Profile": "Density profile of the atmosphere"
      }
    },
    "particles_and_fields_type": {
      "definition": "Fields of an object",
      "examples": {
        "Particles": "Particles in the atmosphere",
        "Cosmic_Rays": "Cosmic rays in the atmosphere",
        "X-Rays": "X-rays in the atmosphere",
        "Gamma-Rays": "Gamma-rays in the atmosphere",
        "Electromagnetic_Waves": "Electromagnetic waves in the atmosphere"
      }
    },
    "dust_type": {
      "definition": "Dust",
      "examples": {
        "Meteoroids": "Dust from meteoroids",
        "IPD": "Interplanetary Dust",
        "Comet": "Dust from comets"
      }
    },
    "ring_type": {
      "definition": "Type of ring",
      "examples": {
        "D": "D ring",
        "C": "C ring",
        "B": "B ring",
        "A": "A ring",
        "F": "F ring",
        "G": "G ring",
        "E": "E ring"
      }
    },
    "ring_division": {
      "definition": "Division of the ring",
      "examples": {
        "Cassini_Division": "Cassini Division",
        "Encke": "Encke Division",
        "Keeler": "Keeler Division"
      }
    },
    "ring_feature": {
      "definition": "Feature of the ring",
      "examples": {
        "Spiral_Bending_Waves": "Spiral Bending Waves",
        "Spokes": "Spokes",
        "Spiral_Density_Waves": "Spiral Density Waves"
      }
    },
    "solar_component_type": {
      "definition": "Solar component",
      "examples": {
        "Corona": "Corona",
        "Solar_Wind": "Solar Wind",
        "Exoplanets": "Exoplanets",
        "Heliosphere": "Heliosphere",
        "Core": "Core",
        "Radiative_Zone": "Radiative Zone",
        "Convective_Zone": "Convective Zone",
        "Photosphere": "Photosphere",
        "Chromosphere": "Chromosphere"
      }
    },
    "solar_system_context": {
      "definition": "Solar system or planetary system as the target context",
      "examples": {
        "Solar_System": "The solar system as an integrated target context"
      }
    },
    "exoplanet_type": {
      "definition": "Type of an exoplanet",
      "examples": {
        "Terrestrial": "Rocky planets, up to 1.5 Earth radii",
        "Gas Giants": "Larger than 10 Earth radii",
        "Ice Giants": "4-6 Earth radii",
        "Super-Earths": "1.5 to 2 Earth radii",
        "Mini-Neptunes": "2-4 Earth radii",
        "Lava Worlds": "Molten rock",
        "Ocean Worlds": "Global oceans",
        "Rogue Planets": "Planets not bound to a star"
      }
    },
    "feature_name": {
      "definition": "Name of the feature"
    },
    "feature_type": {
      "definition": "Type of the feature",
      "examples": {
        "Albedo": "Geographic area distinguished by amount of reflected light",
        "Arcus": "Arc-shaped feature",
        "Astronaut_Named_Feature": "Lunar features at or near Apollo landing sites",
        "Catena": "Chain of craters",
        "Chaos": "Distinctive area of broken terrain",
        "Chasma": "A deep, elongated, steep-sided depression",
        "Cloud": "Atmospheric cloud formation",
        "Corona": "Ovoid-shaped volcanic feature",
        "Collis": "Small hills or knobs",
        "Crater": "Impact depression on a surface",
        "Dorsum": "Ridge",
        "Dunes": "Unda, undae.  Moving sand dunes",
        "Eruptive_Center": "Active volcanic center on Io",
        "Fluctus": "Flow terrain",
        "Fossa": "Long, narrow depression",
        "Insula": "Island (islands), an isolated land area surrounded by liquid",
        "Linea": "A dark or bright elongate marking, curved or straight",
        "Mensa": "A flat-topped prominence with cliff-like edges",
        "Marcula": "Dark spot, may be irregular",
        "Mons": "Mountain elevated landform",
        "Mare": "Dark plains on the Moon",
        "Oceanus": "A very large dark area on the moon",
        "Planum": "Plateau or high plain",
        "Plume": "Cryo-volcanic features on Triton",
        "Pits": "Small pits on the surface",
        "Pingo": "Ice mound",
        "Planitia": "Flat surface",
        "Regio": "A large area marked by reflectivity",
        "Rima": "Fissure",
        "Ring": "Planetary rings",
        "Rupes": "Scarp",
        "Saxum": "Bolder or rock",
        "Sulcus": "Subparallel furrows and ridges",
        "Terra": "Terra, terrae.  Extensive land mass",
        "Tholus": "Small domical mountain or hill",
        "Valley": "Vallis, Valles, Elongated depression",
        "Volcano": "Volcanic landform",
        "Virga": "A streak or stripe or color"
      }
    },
    "material_type": {
      "definition": "Material type of the object",
      "examples": {
        "Rock": "Solid mineral material",
        "Ice": "Frozen water or other volatiles",
        "Gas": "Gaseous material",
        "Dust": "Fine particulate material",
        "Regolith": "Surface layer of loose material",
        "Liquid": "Liquid state material"
      }
    },
    "process_type": {
      "definition": "Type of process being studied.",
      "examples": {
        "Impact": "Collision processes",
        "Volcanic": "Volcanic activity",
        "Tectonic": "Crustal deformation processes",
        "Atmospheric": "Atmospheric processes",
        "Erosional": "Surface degradation processes"
      }
    },
    "composition_type": {
      "definition": "Primary composition of the material being studied.",
      "examples": {
        "Silicate": "Composed primarily of silicate minerals",
        "Metal": "Composed primarily of metallic elements",
        "Organic": "Composed primarily of organic compounds",
        "Icy": "Composed primarily of water or other volatile ices",
        "Gaseous": "Composed primarily of gas",
        "Mixed": "Composed of a mixture of different materials"
      }
    },
    "temperature_regime": {
      "definition": "Temperature conditions at the study location.",
      "examples": {
        "Cryogenic": "Extremely low temperatures, typically below 120K",
        "Cold": "Below freezing but not extreme",
        "Temperate": "Near-surface temperatures typical of Earth",
        "Warm": "Above freezing and below boiling point",
        "Hot": "Above boiling point"
      }
    },
    "pressure_conditions": {
      "definition": "Pressure conditions at the study location.",
      "examples": {
        "Vacuum": "Essentially no atmospheric pressure",
        "Very_Low": "Minimal atmospheric pressure like Mars",
        "Earth_Like": "Similar to Earth's atmospheric pressure",
        "High": "Higher than Earth's atmospheric pressure",
        "Extreme": "Very high pressure like Venus surface or gas giant interiors",
        "Variable": "Significant pressure variations or gradients"
      }
    },
    "radiation_environment": {
      "definition": "Radiation conditions at the study location.",
      "examples": {
        "Low": "Minimal radiation exposure like Earth surface",
        "Moderate": "Similar to Earth orbit or Mars surface",
        "High": "Significant radiation like Jupiter radiation belts",
        "Extreme": "Very high radiation levels",
        "Shielded": "Protected or shielded from external radiation"
      }
    },
    "atmospheric_presence": {
      "definition": "Presence and nature of atmosphere at the study location.",
      "examples": {
        "None": "No atmosphere present",
        "Trace": "Very low atmospheric pressure",
        "Low": "Atmospheric pressure similar to Earth's",
        "High": "Atmospheric pressure similar to Earth's",
        "Extreme": "Very high atmospheric pressure like Venus surface",
        "Variable": "Significant atmospheric pressure variations or gradients"
      }
    },
    "collection_method": {
      "definition": "Method used to collect the data.",
      "examples": {
        "Orbiter": "Data collected by an orbiting spacecraft",
        "Lander": "Data collected by a surface lander",
        "Rover": "Data collected by a mobile surface rover",
        "Flyby": "Data collected by a cruising spacecraft during a target encounter",
        "Telescope": "Data collected by Earth-based or space telescopes",
        "Sample_Return": "Analysis of returned physical samples",
        "Laboratory": "Data collected in laboratory settings",
        "Modeling": "Data generated by simulation"
      }
    },
    "instrument_type": {
      "definition": "Type of instrument used to collect the data.",
      "examples": {
        "Spectrometer": "Instrument that measures spectra",
        "Imager": "Imaging device",
        "Radar": "Radio detection and ranging instrument",
        "LiDAR": "Light detection and ranging instrument",
        "Seismometer": "Instrument that measures ground motion",
        "Magnetometer": "Instrument that measures magnetic fields",
        "Mass_Spectrometer": "Instrument that measures mass of molecules",
        "Dust_Particle_Detector": "Instrument that detects dust or particles"
      }
    },
    "data_category": {
      "definition": "General category of the collected data.",
      "examples": {
        "Altimetry": "Elevation data",
        "Image": "Visual representation data",
        "Photometry": "Photometric measurement data",
        "Map": "Representation of higher ordered data in a spatial context",
        "Model": "Results from computational models",
        "Simulation": "Results from computational simulations",
        "Database": "Flat rendering of existing data base",
        "Big_Data": "Large-scale data collection or analysis products",
        "Parameter_Data": "Numerical data"
      }
    },
    "data_format": {
      "definition": "Format of the collected data.",
      "examples": {
        "Shape_Model_DTM": "A 3D model of the surface of the object",
        "Geologic_Map": "A map of the geologic features of the object",
        "Thermal_Map": "A map of the thermal properties of the object",
        "Mosaic": "A composite image of the object",
        "Spectral_Map": "A map of the spectral properties of the object",
        "Gazetteer": "A list of feature names",
        "Time_Series": "Sequential data collected over time",
        "Crater": "A list of craters on the object",
        "Light_Curve": "A list of light curves on the object",
        "Spectral": "A list of spectra on the object",
        "Physical_Properties": "A list of physical properties of the object",
        "Photometric_Properties": "A list of photometric properties of the object",
        "Gravity_Map": "A map of the gravity of the object",
        "Taxonomies": "A list of taxonomies of the object",
        "Crater_Type": "A list of irregular crater types on the object"
      }
    },
    "earth_geologic_epoch": {
      "definition": "Temporal epoch of the Earth",
      "examples": {
        "Eoarchean": "Earth's 4,031 to 3,600 million years ago",
        "Paleoarchean": "Earth's 3,600 to 3,200 million years ago",
        "Mesoarchean": "Earth's 3,200 to 2,800 million years ago",
        "Neoarchean": "Earth's 2,800 to 2,500 million years ago",
        "Paleoproterozoic": "Earth's 2,500 to 1,600 million years ago",
        "Mesoproterozoic": "Earth's 1,600 to 1,000 million years ago",
        "Neoproterozoic": "Earth's 1,000 to 538.8 million years ago",
        "Paleozoic": "Earth's 238.8 to 251.9 million years ago",
        "Mesozoic": "Earth's 251.9 to 66 million years ago",
        "Cenozoic": "Earth's 66-0 million years ago"
      }
    },
    "moon_geologic_epoch": {
      "definition": "Temporal epoch of the Moon",
      "examples": {
        "Pre-Nectarian": "Moon, 4,533 to 3,920 million years ago",
        "Nectarian": "Moon3,920 to 3,850 million years ago",
        "Imbrian": "Moon 3,850 to 3,200 million years ago",
        "Eratosthenian": "Moon 3,200 to 1,100 million years ago",
        "Copernican": "Moon 1,100 to 0 million years ago"
      }
    },
    "mars_geologic_epoch": {
      "definition": "Temporal epoch of Mars",
      "examples": {
        "Pre-Noachian": "Mars 4,500 to 4,100 million years ago",
        "Noachian": "Mars 4,100 to 3,700 million years ago",
        "Hesperian": "Mars 3,700 to 3,000 million years ago",
        "Amazonian": "Mars 3,000 to 0 million years ago"
      }
    },
    "vesta_geologic_epoch": {
      "definition": "Relative timescale for Vesta",
      "examples": {
        "Pre-Veneneia": "~4,100 million years ago",
        "Veneneia": "~4,100 million years ago",
        "Rheasilvia": "~3,900 million years ago",
        "Marcia": "~3,500 million years ago"
      }
    },
    "ceres_geologic_epoch": {
      "definition": "Relative timescale for Ceres",
      "examples": {
        "Pre-Kerwan": "~4,560 to 4,000 million years ago",
        "Kerwan": "4,000 to 2,500 million years ago",
        "Ernutet": "~ 2.500 to 0 million years ago"
      }
    },
    "research_goals": {
      "definition": "What was the goal of the research endeavor"
    },
    "related_publications": {
      "definition": "Related publications of the study"
    },
    "keywords": {
      "definition": "Suggested keywords to describe your study"
    },
    "principal_investigator": {
      "definition": "Principal investigator of the project if different from the data set"
    },
    "institution": {
      "definition": "Institution of the study"
    },
    "data_visualization_software": {
      "definition": "Visualization software which may include analysis tools",
      "examples": {
        "JMARS": "Java Mission-planning and Analysis for Remote Sensing",
        "ISIS3": "Integrated Software for Imagers and Spectrometers",
        "IDL": "Interactive Data Language",
        "ENVI": "Environment for Visualizing Images",
        "ArcGIS": "Geographic Information System (GIS) developed by ESRI",
        "QGIS": "Quantum Geographic Information System",
        "R": "Data analysis tool",
        "MATLAB": "Matrix Laboratory",
        "SBMT": "Small Body Mapping Tool",
        "Python": "To include SciPy, NumPy, AstroPy, SpiceyPy",
        "AstroPy": "Astronomy Python library",
        "PlanetaryPy": "Planetary science Python library",
        "IRAF": "Image Reduction and Analysis Facility",
        "DS9": "FITS Image Display",
        "GDAL": "Geospatial Data Abstraction Library",
        "GMT": "Generic Mapping Tools"
      }
    },
    "modeling_software": {
      "definition": "Key modeling software",
      "examples": {
        "GISS ROCKE-3D": "Java Mission-planning and Analysis for Remote Sensing",
        "GEODYN": "Integrated Software for Imagers and Spectrometers",
        "Melts": "Magmatic Equilibrium Liquidus Temperature Software for cosmochemistry",
        "COMSOL Multiphysics": "Simulating physical processes",
        "FLASH": "FLASH/ Athena/PLUTO",
        "iSALE": "Shock physics code for impact cratering, planetary interior",
        "HYDRA": "multi-material Eulerian code",
        "SPH": "Smoothed Particle Hydrodynamics",
        "CTH": "Collide, Track, Hydrodynamics",
        "LSDYNA": "Finite element analysis (FEA) code",
        "SPLAT": "SPectral Luminance and Temperature",
        "MYSTIC": "Radiative transfer modeling"
      }
    },
    "orbital_mechanics_software": {
      "definition": "Software used for navigation or modeling",
      "examples": {
        "GMAT": "General Mission Analysis Tool",
        "STK": "Satellite/System Tool Kit",
        "SPICE": "SPICE Toolkit from NAIF",
        "Orekit": "Orbital mechanics and space flight dynamics",
        "Simulink": "Add-on for MatLAB",
        "Celestia": "Astronomy, orbital visualization",
        "Rebound": "N-body simulations",
        "Mercury": "N-body code",
        "Swift": "N-body simulations"
      }
    },
    "digital_terrain_modeling_software": {
      "definition": "Key modeling software",
      "examples": {
        "SPC": "Stereophotoclinometry",
        "Stereo": "Photogrammetry",
        "Ames Stereo Pipeline": "Ames Pipeline",
        "SOCET Set": "SOCET Set",
        "Shape_From_Shading": "Shape from shading technique",
        "Shape_From_Modeling": "DTM generated from shape from motion technique"
      }
    },
    "other_software": {
      "definition": "Any software not covered by other values"
    }
  }
};
