
// This file is automatically generated from the YAML data dictionary
export const data = {
  "classes": {
    "Scientific_Discipline": {
      "definition": "Information about the scientific discipline and research context.",
      "element_flag": true,
      "attributes": [
        "Study_Focus",
        "Scientific_fields",
        "Investigation_Technique"
      ],
      "nested_classes": {}
    },
    "Target_Object": {
      "definition": "Information about the target of observation, whether it is a celestial body, feature, or other object.",
      "element_flag": true,
      "attributes": [
        "Object_Name",
        "Parent_Body",
        "Scope"
      ],
      "nested_classes": {
        "Object_Type": {
          "attributes": [
            "Planet",
            "Particles and Fields",
            "Dust",
            "Solar_Component",
            "Exoplanet"
          ],
          "nested_classes": {
            "Small_Body": {
              "attributes": [
                "Asteroid",
                "TNO",
                "Centaur",
                "KBO",
                "Oort_Cloud",
                "Comet",
                "Satellite"
              ],
              "nested_classes": {}
            },
            "Atmosphere": {
              "attributes": [
                "Layer",
                "Study_Type"
              ],
              "nested_classes": {}
            },
            "Rings": {
              "attributes": [
                "Ring_Type",
                "Ring_Division",
                "Ring_Feature"
              ],
              "nested_classes": {}
            }
          }
        },
        "Feature": {
          "attributes": [
            "Name",
            "Type"
          ],
          "nested_classes": {}
        },
        "Physical_Properties": {
          "attributes": [
            "Material_Type",
            "Process_Type",
            "Composition"
          ],
          "nested_classes": {}
        },
        "Environmental_Context": {
          "attributes": [
            "Temperature_Regime",
            "Pressure_Conditions",
            "Radiation_Environment",
            "Atmospheric_Presence"
          ],
          "nested_classes": {}
        }
      }
    },
    "Data_Collection": {
      "definition": "Information about how the data was collected and its format.",
      "element_flag": true,
      "attributes": [
        "Collection_Method",
        "Instrument_Type",
        "Data_Category",
        "Data_Format"
      ],
      "nested_classes": {
        "Temporal_Epoch": {
          "attributes": [
            "Earth",
            "Moon",
            "Mars",
            "Vesta",
            "Ceres"
          ],
          "nested_classes": {}
        }
      }
    },
    "Research_Context": {
      "definition": "Information about the research context and associated metadata.",
      "element_flag": true,
      "attributes": [
        "Research_Goals",
        "Related_Publications",
        "Keywords",
        "Principal_Investigator",
        "Institution"
      ],
      "nested_classes": {
        "Software_Used": {
          "attributes": [
            "Data Visualization",
            "Modeling",
            "Orbital Mechanics & Mission Support",
            "Digital Terrain Modeling",
            "Other"
          ],
          "nested_classes": {}
        }
      }
    },
    "Object_Type": {
      "definition": "Select the categories within which the data would fit into",
      "element_flag": false,
      "attributes": [
        "Planet",
        "Particles and Fields",
        "Dust",
        "Solar_Component",
        "Exoplanet"
      ],
      "nested_classes": {
        "Small_Body": {
          "attributes": [
            "Asteroid",
            "TNO",
            "Centaur",
            "KBO",
            "Oort_Cloud",
            "Comet",
            "Satellite"
          ],
          "nested_classes": {}
        },
        "Atmosphere": {
          "attributes": [
            "Layer",
            "Study_Type"
          ],
          "nested_classes": {}
        },
        "Rings": {
          "attributes": [
            "Ring_Type",
            "Ring_Division",
            "Ring_Feature"
          ],
          "nested_classes": {}
        }
      }
    },
    "Small_Body": {
      "definition": "Small body",
      "element_flag": false,
      "attributes": [
        "Asteroid",
        "TNO",
        "Centaur",
        "KBO",
        "Oort_Cloud",
        "Comet",
        "Satellite"
      ],
      "nested_classes": {}
    },
    "Atmosphere": {
      "definition": "Atmosphere of a celestial body",
      "element_flag": false,
      "attributes": [
        "Layer",
        "Study_Type"
      ],
      "nested_classes": {}
    },
    "Rings": {
      "definition": "Rings of an object",
      "element_flag": false,
      "attributes": [
        "Ring_Type",
        "Ring_Division",
        "Ring_Feature"
      ],
      "nested_classes": {}
    },
    "Feature": {
      "definition": "Feature",
      "element_flag": false,
      "attributes": [
        "Name",
        "Type"
      ],
      "nested_classes": {}
    },
    "Physical_Properties": {
      "definition": "Information about the physical properties of the object under study.",
      "element_flag": false,
      "attributes": [
        "Material_Type",
        "Process_Type",
        "Composition"
      ],
      "nested_classes": {}
    },
    "Environmental_Context": {
      "definition": "Information about the environmental conditions at the study location.",
      "element_flag": false,
      "attributes": [
        "Temperature_Regime",
        "Pressure_Conditions",
        "Radiation_Environment",
        "Atmospheric_Presence"
      ],
      "nested_classes": {}
    },
    "Temporal_Epoch": {
      "definition": "The temporal epoch of the data collection.",
      "element_flag": false,
      "attributes": [
        "Earth",
        "Moon",
        "Mars",
        "Vesta",
        "Ceres"
      ],
      "nested_classes": {}
    },
    "Software_Used": {
      "definition": "Software used to analyze the data.",
      "element_flag": false,
      "attributes": [
        "Data Visualization",
        "Modeling",
        "Orbital Mechanics & Mission Support",
        "Digital Terrain Modeling",
        "Other"
      ],
      "nested_classes": {}
    }
  },
  "attributes": {
    "Study_Focus": {
      "definition": "High-level research focus.",
      "permissible_values": {
        "Surface": "Study focused on planetary geology such as features or properties",
        "Interior": "Study focused on internal structure or processes",
        "Atmosphere": "Study focused on atmospheric properties or dynamics",
        "Magnetosphere": "Study focused on magnetic field properties or interactions",
        "Orbital_Dynamics": "Study focused on orbital properties or behaviors",
        "Composition": "Study focused on chemical or mineral composition",
        "Plasma": "Study of plasma and ionospheres",
        "Space Weather": "Study of the change in surfaces due to space weather effects",
        "Planetary Protection": "Study focused on planetary protection",
        "Rings": "Study focused on ring and ring-moon systems",
        "Resources": "In-situ resource characterization and utilization",
        "Other": "Any focus not covered by other values"
      }
    },
    "Scientific_fields": {
      "definition": "What are the different scientific fields of study.",
      "permissible_values": {
        "Astrobiology": "Study of life in the universe",
        "Astronomy_Observation": "Observation of celestial objects",
        "Astronomy_Radar": "Radar observations of celestial objects",
        "Astronomy_Exoplanets": "Study of exoplanets",
        "Astronomy_Spectroscopy": "Spectroscopy of celestial objects",
        "Geology_Geophysics": "Geophysics of the Earth and other planets",
        "Geology_Seismology": "Seismology of the Earth and other planets",
        "Geology_Surface": "Surface studies of the Earth and other planets",
        "Geology_Crater_Counting": "Crater counting of the Earth and other planets",
        "Geology_Interior_Studies": "Interior studies of the Earth and other planets",
        "Dynamics": "Dynamics of the Earth and other planets",
        "Laboratory_Geochemistry": "Geochemistry of physical samples",
        "Laboratory_Cosmochemistry": "Cosmochemistry of physical samples",
        "Laboratory_Age_Dating": "Age dating of physical samples",
        "Laboratory_Analytic_Chemistry": "Analytic chemistry of physical samples",
        "Laboratory_Spectral_Analysis": "Spectral analysis of physical samples",
        "Atmospheric_Study": "Atmospheric studies of the Earth and other planets",
        "Impact": "Measuring and categorizing impact craters and rates",
        "Hydrology": "Fluvial mechanics",
        "Exoplanets": "Detection and characterizing exoplanets",
        "Modeling": "Modeling of the Earth and other planets",
        "Magnetospheres": "Magnetospheres of the Earth and other planets",
        "Space_Physics": "Space physics of the Earth and other planets",
        "Other": "Any field not covered by other values"
      }
    },
    "Investigation_Technique": {
      "definition": "What method of scientific investigations are used.",
      "permissible_values": {
        "Spectroscopy": "Collection of spectra",
        "Modeling": "Computer-based simulation or modeling",
        "Mapping": "Collection of maps",
        "Radar": "Collection of radar data",
        "Seismology": "Collection of seismic data",
        "Ground based observation": "Data that was derived from Earth-based telescopes",
        "Gravimetry": "Collection of gravity data",
        "Remove Sensing": "Various data collected via remote sensing techniques",
        "LiDAR": "Light Detection and Ranging",
        "Geochemistry": "Collection of geochemical/cosmochmical data",
        "Laboratory": "Various laboratory work",
        "Data analysis": "General analysis of data",
        "Artificial Intelligence": "AI and machine learning techniques",
        "ICPMS": "Collection of inductively coupled plasma mass spectrometry data",
        "Other": "Any investigation technique not covered by other values"
      }
    },
    "Object_Name": {
      "definition": "Name of the object"
    },
    "Parent_Body": {
      "definition": "Parent body of the object"
    },
    "Scope": {
      "definition": "Scope of the data collection",
      "permissible_values": {
        "Global": "Data collected from the entire object",
        "Regional": "Data collected from a large region of the object",
        "Local": "Data collected from a small location on the object",
        "Other": "Any scope not covered by other values"
      }
    },
    "Asteroid": {
      "definition": "Asteroid",
      "permissible_values": {
        "Near_Earth": "Asteroids with orbits that bring them close to Earth",
        "Trojan": "Asteroids that share an orbit with a planet",
        "Active": "Asteroids that show comet-like activity",
        "Main_Belt": "Asteroids in the main asteroid belt",
        "PHA": "Potential Hazardous Asteroid",
        "Other": "Any asteroid type not covered by other values"
      }
    },
    "TNO": {
      "definition": "Trans-Neptunian Object",
      "permissible_values": {
        "Classical": "Objects in the classical Kuiper belt",
        "Resonant": "Objects in orbital resonance with Neptune",
        "Scattered": "Objects scattered by Neptune",
        "Detached": "Objects with orbits not strongly influenced by Neptune",
        "Other": "Any TNO type not covered by other values"
      }
    },
    "Centaur": {
      "definition": "Centaur",
      "permissible_values": {
        "Active": "Centaurs showing comet-like activity",
        "Inactive": "Centaurs without comet-like activity",
        "Other": "Any centaur type not covered by other values"
      }
    },
    "KBO": {
      "definition": "Kuiper Belt Object",
      "permissible_values": {
        "Classical": "Objects in the classical Kuiper belt",
        "Resonant": "Objects in orbital resonance with Neptune",
        "Scattered": "Objects scattered by Neptune",
        "Other": "Any KBO type not covered by other values"
      }
    },
    "Oort_Cloud": {
      "definition": "Oort Cloud Object",
      "permissible_values": {
        "Inner": "Objects in the inner Oort cloud",
        "Outer": "Objects in the outer Oort cloud",
        "Other": "Any Oort cloud type not covered by other values"
      }
    },
    "Comet": {
      "definition": "Comet",
      "permissible_values": {
        "Jupiter_Family": "Comets that orbit Jupiter",
        "Single_Pass": "Comets that pass through the inner solar system",
        "Other": "Any comet type not covered by other values"
      }
    },
    "Satellite": {
      "definition": "Satellite",
      "permissible_values": {
        "Icy_Moons": "Icy moons of a planet",
        "Galilean_Moons": "Galilean moons of Jupiter",
        "Irregular_Moons": "Irregular moons of a planet",
        "Captured_Moons": "Captured moons of a planet",
        "Shepherding_Moon": "Shepherding moon of a planet",
        "Other": "Any satellite type not covered by other values"
      }
    },
    "Planet": {
      "definition": "Planet",
      "permissible_values": {
        "Gas_Giant": "Large planets composed mainly of gas",
        "Terrestrial": "Rocky planets similar to Earth",
        "Interior": "Planets closer to the Sun than Earth",
        "Other": "Any planet type not covered by other values"
      }
    },
    "Layer": {
      "definition": "Layer of the atmosphere",
      "permissible_values": {
        "Troposphere": "Lowest layer of the atmosphere",
        "Stratosphere": "Layer above the troposphere",
        "Ionosphere": "Layer containing ions",
        "Exosphere": "Outermost layer of the atmosphere",
        "Other": "Any atmospheric layer not covered by other values"
      }
    },
    "Study_Type": {
      "definition": "Type of study of the atmosphere",
      "permissible_values": {
        "Temperature_Profile": "Temperature profile of the atmosphere",
        "Scale_Height": "Scale height of the atmosphere",
        "Density_Profile": "Density profile of the atmosphere"
      }
    },
    "Particles and Fields": {
      "definition": "Fields of an object",
      "permissible_values": {
        "Particles": "Particles in the atmosphere",
        "Cosmic_Rays": "Cosmic rays in the atmosphere",
        "X-Rays": "X-rays in the atmosphere",
        "Gamma-Rays": "Gamma-rays in the atmosphere",
        "Electromagnetic_Waves": "Electromagnetic waves in the atmosphere"
      }
    },
    "Dust": {
      "definition": "Dust",
      "permissible_values": {
        "Meteoroids": "Dust from meteoroids",
        "IPD": "Interplanetary Dust",
        "Comet": "Dust from comets",
        "Other": "Other dust"
      }
    },
    "Ring_Type": {
      "definition": "Type of ring",
      "permissible_values": {
        "D": "D ring",
        "C": "C ring",
        "B": "B ring",
        "A": "A ring",
        "F": "F ring",
        "G": "G ring",
        "E": "E ring"
      }
    },
    "Ring_Division": {
      "definition": "Division of the ring",
      "permissible_values": {
        "Cassini_Division": "Cassini Division",
        "Encke": "Encke Division",
        "Keeler": "Keeler Division"
      }
    },
    "Ring_Feature": {
      "definition": "Feature of the ring",
      "permissible_values": {
        "Spiral_Bending_Waves": "Spiral Bending Waves",
        "Spokes": "Spokes",
        "Spiral_Density_Waves": "Spiral Density Waves"
      }
    },
    "Solar_Component": {
      "definition": "Solar component",
      "permissible_values": {
        "Corona": "Corona",
        "Solar_Wind": "Solar Wind",
        "Exoplanets": "Exoplanets",
        "Heliosphere": "Heliosphere",
        "Core": "Core",
        "Radiative_Zone": "Radiative Zone",
        "Convective_Zone": "Convective Zone",
        "Photosphere": "Photosphere",
        "Chromosphere": "Chromosphere",
        "Other": "Any solar component not covered by other values"
      }
    },
    "Exoplanet": {
      "definition": "Type of an exoplanet",
      "permissible_values": {
        "Terrestrial": "Rocky planets, up to 1.5 Earth radii",
        "Gas Giants": "Larger than 10 Earth radii",
        "Ice Giants": "4-6 Earth radii",
        "Super-Earths": "1.5 to 2 Earth radii",
        "Mini-Neptunes": "2-04 Earth radii",
        "Lava Worlds": "Molten rock",
        "Ocean Worlds": "Global oceans",
        "Rogue Planets": "Planets not bound to a star",
        "Other": "Other categories"
      }
    },
    "Name": {
      "definition": "Name of the feature"
    },
    "Type": {
      "definition": "Type of the feature",
      "permissible_values": {
        "Albedo": "Geographic area distinguished by amount of reflected light",
        "Arcus": "Arc-shaped feature",
        "Astronaut_Named_Feature": "Lunar features at or near Apollo landing sites",
        "Catena": "Chain of craters",
        "Chaos": "Distinctive area of broken terrain",
        "Chasma": "A deep, elongated, steep-sided depression",
        "Cloud": "Atmospheric cloud formation",
        "Corona": "Ovoid-shaped volcanic feature",
        "Collis": "Small hills or knobs",
        "Crater": "Impact depression on a surface",
        "Dorsum": "Ridge",
        "Dunes": "Unda, undae.  Moving sand dunes",
        "Eruptive_Center": "Active volcanic center on Io",
        "Fluctus": "Flow terrain",
        "Fossa": "Long, narrow depression",
        "Insula": "Island (islands), an isolated land area surrounded by liquid",
        "Linea": "A dark or bright elongate marking, curved or straight",
        "Mensa": "A flat-topped prominence with cliff-like edges",
        "Marcula": "Dark spot, may be irregular",
        "Mons": "Mountain elevated landform",
        "Mare": "Dark plains on the Moon",
        "Oceanus": "A very large dark area on the moon",
        "Planum": "Plateau or high plain",
        "Plume": "Cryo-volcanic features on Triton",
        "Pits": "Small pits on the surface",
        "Pingo": "Ice mound",
        "Planitia": "Flat surface",
        "Regio": "A large area marked by reflectivity",
        "Rima": "Fissure",
        "Ring": "Planetary rings",
        "Rupes": "Scarp",
        "Saxum": "Bolder or rock",
        "Sulcus": "Subparallel furrows and ridges",
        "Terra": "Terra, terrae.  Extensive land mass",
        "Tholus": "Small domical mountain or hill",
        "Valley": "Vallis, Valles, Elongated depression",
        "Volcano": "Volcanic landform",
        "Virga": "A streak or stripe or color",
        "Other": "Any feature type not covered by other values"
      }
    },
    "Material_Type": {
      "definition": "Material type of the object",
      "permissible_values": {
        "Rock": "Solid mineral material",
        "Ice": "Frozen water or other volatiles",
        "Gas": "Gaseous material",
        "Dust": "Fine particulate material",
        "Regolith": "Surface layer of loose material",
        "Liquid": "Liquid state material",
        "Other": "Any material type not covered by other values"
      }
    },
    "Process_Type": {
      "definition": "Type of process being studied.",
      "permissible_values": {
        "Impact": "Collision processes",
        "Volcanic": "Volcanic activity",
        "Tectonic": "Crustal deformation processes",
        "Atmospheric": "Atmospheric processes",
        "Erosional": "Surface degradation processes",
        "Other": "Any process type not covered by other values"
      }
    },
    "Composition": {
      "definition": "Primary composition of the material being studied.",
      "permissible_values": {
        "Silicate": "Composed primarily of silicate minerals",
        "Metal": "Composed primarily of metallic elements",
        "Organic": "Composed primarily of organic compounds",
        "Icy": "Composed primarily of water or other volatile ices",
        "Gaseous": "Composed primarily of gas",
        "Mixed": "Composed of a mixture of different materials",
        "Other": "Any composition not covered by other values"
      }
    },
    "Temperature_Regime": {
      "definition": "Temperature conditions at the study location.",
      "permissible_values": {
        "Cryogenic": "Extremely low temperatures, typically below 120K",
        "Cold": "Below freezing but not extreme",
        "Temperate": "Near-surface temperatures typical of Earth",
        "Warm": "Above freezing and below boiling point",
        "Hot": "Above boiling point",
        "Other": "Any temperature regime not covered by other values"
      }
    },
    "Pressure_Conditions": {
      "definition": "Pressure conditions at the study location.",
      "permissible_values": {
        "Vacuum": "Essentially no atmospheric pressure",
        "Very_Low": "Minimal atmospheric pressure like Mars",
        "Earth_Like": "Similar to Earth's atmospheric pressure",
        "High": "Higher than Earth's atmospheric pressure",
        "Extreme": "Very high pressure like Venus surface or gas giant interiors",
        "Variable": "Significant pressure variations or gradients",
        "Other": "Any pressure condition not covered by other values"
      }
    },
    "Radiation_Environment": {
      "definition": "Radiation conditions at the study location.",
      "permissible_values": {
        "Low": "Minimal radiation exposure like Earth surface",
        "Moderate": "Similar to Earth orbit or Mars surface",
        "High": "Significant radiation like Jupiter radiation belts",
        "Extreme": "Very high radiation levels",
        "Shielded": "Protected or shielded from external radiation",
        "Other": "Any radiation environment not covered by other values"
      }
    },
    "Atmospheric_Presence": {
      "definition": "Presence and nature of atmosphere at the study location.",
      "permissible_values": {
        "None": "No atmosphere present",
        "Trace": "Very low atmospheric pressure",
        "Low": "Atmospheric pressure similar to Earth's",
        "High": "Atmospheric pressure similar to Earth's",
        "Extreme": "Very high atmospheric pressure like Venus surface",
        "Variable": "Significant atmospheric pressure variations or gradients",
        "Other": "Any atmospheric presence not covered by other values"
      }
    },
    "Collection_Method": {
      "definition": "Method used to collect the data.",
      "permissible_values": {
        "Orbiter": "Data collected by an orbiting spacecraft",
        "Lander": "Data collected by a surface lander",
        "Rover": "Data collected by a mobile surface rover",
        "Telescope": "Data collected by Earth-based or space telescopes",
        "Sample_Return": "Analysis of returned physical samples",
        "Laboratory": "Data collected in laboratory settings",
        "Modeling": "Data generated by simulation",
        "Other": "Any collection method not covered by other values"
      }
    },
    "Instrument_Type": {
      "definition": "Type of instrument used to collect the data.",
      "permissible_values": {
        "Spectrometer": "Instrument that measures spectra",
        "Imager": "Imaging device",
        "Radar": "Radio detection and ranging instrument",
        "LiDAR": "Light detection and ranging instrument",
        "Seismometer": "Instrument that measures ground motion",
        "Magnetometer": "Instrument that measures magnetic fields",
        "Mass_Spectometer": "Instrument that measures mass of molecules",
        "Dust_Particle_Detector": "Instrument that detects dust or particles",
        "Other": "Any instrument type not covered by other values"
      }
    },
    "Data_Category": {
      "definition": "General category of the collected data.",
      "permissible_values": {
        "Altimetry": "Elevation data",
        "Image": "Visual representation data",
        "Photometry": "Photometric measurement data",
        "Map": "Representation of higher ordered data in a spatial context",
        "Model": "Results from computational models",
        "Database": "Flat rendering of existing data base",
        "Parameter_Data": "Numerical data",
        "Other": "Any data category not covered by other values"
      }
    },
    "Data_Format": {
      "definition": "Format of the collected data.",
      "permissible_values": {
        "Shape_Model_DTM": "A 3D model of the surface of the object",
        "Geologic_Map": "A map of the geologic features of the object",
        "Thermal_Map": "A map of the thermal properties of the object",
        "Mosaic": "A composite image of the object",
        "Spectral_Map": "A map of the spectral properties of the object",
        "Gazetteer": "A list of feature names",
        "Time_Series": "Sequential data collected over time",
        "Crater": "A list of craters on the object",
        "Light_Curve": "A list of light curves on the object",
        "Spectral": "A list of spectra on the object",
        "Physical_Properties": "A list of physical properties of the object",
        "Photometric_Properties": "A list of photometric properties of the object",
        "Gravity_Map": "A map of the gravity of the object",
        "Taxonomies": "A list of taxonomies of the object",
        "Crater_Type": "A list of irregular crater types on the object",
        "Other": "Any data format not covered by other values"
      }
    },
    "Earth": {
      "definition": "Temporal epoch of the Earth",
      "permissible_values": {
        "Eoarchean": "Earth's 4,031 to 3,600 million years ago",
        "Paleoarchean": "Earth's 3,600 to 3,200 million years ago",
        "Mesoarchean": "Earth's 3,200 to 2,800 million years ago",
        "Neoarchean": "Earth's 2,800 to 2,500 million years ago",
        "Paleoproterozoic": "Earth's 2,500 to 1,600 million years ago",
        "Mesoproterozoic": "Earth's 1,600 to 1,000 million years ago",
        "Neoproterozoic": "Earth's 1,000 to 538.8 million years ago",
        "Paleozoic": "Earth's 238.8 to 251.9 million years ago",
        "Mesozoic": "Earth's 251.9 to 66 million years ago",
        "Cenozoic": "Earth's 66-0 million years ago",
        "Ohter": "Earth's Paleozoic Era"
      }
    },
    "Moon": {
      "definition": "Temporal epoch of the Moon",
      "permissible_values": {
        "Pre-Nectarian": "Moon, 4,533 to 3,920 million years ago",
        "Nectarian": "Moon3,920 to 3,850 million years ago",
        "Imbrian": "Moon 3,850 to 3,200 millino years ago",
        "Eratosthenian": "Moon 3,200 to 1,100 million years ago",
        "Copernican": "Moon 1,100 to 0 million years ago"
      }
    },
    "Mars": {
      "definition": "Temporal epoch of Mars",
      "permissible_values": {
        "Pre-Noachian": "Mars 4,500 to 4,100 million years ago",
        "Noachian": "Mars 4,100 to 3,700 million years ago",
        "Hesperian": "Mars 3,700 to 3,000 million years ago",
        "Amazonian": "Mars 3,000 to 0 million years ago"
      }
    },
    "Vesta": {
      "definition": "Relative timescale for Vesta",
      "permissible_values": {
        "Pre-Veneneia": "~4,100 million years ago",
        "Veneneia": "~4,100 million years ago",
        "Rheasilvia": "~3,900 million years ago",
        "Marcia": "~3,500 million years ago"
      }
    },
    "Ceres": {
      "definition": "Relative timescale for Ceres",
      "permissible_values": {
        "Pre-Kerwan": "~4,560 to 4,000 million years ago",
        "Kerwan": "4,000 to 2,500 million years ago",
        "Ernutet": "~ 2.500 to 0 million years ago"
      }
    },
    "Research_Goals": {
      "definition": "What was the goal of the research endeavor",
      "permissible_values": {
        "Other": "Any research goal not covered by other values"
      }
    },
    "Related_Publications": {
      "definition": "Related publications of the study"
    },
    "Keywords": {
      "definition": "Suggested keywords to describe your study"
    },
    "Principal_Investigator": {
      "definition": "Principal investigator of the project if different from the data set"
    },
    "Institution": {
      "definition": "Institution of the study"
    },
    "Data Visualization": {
      "definition": "Visualization software which may include analysis tools",
      "permissible_values": {
        "JMARS": "Java Mission-planning and Analysis for Remote Sensing",
        "ISIS3": "Integrated Software for Imagers and Spectrometers",
        "IDL": "Interactive Data Language",
        "ENVI": "Environment for Visualizing Images",
        "ArcGIS": "Geographic Information System (GIS) developed by ESRI",
        "QGIS": "Quantum Geographic Information System",
        "R": "Data analysis tool",
        "MATLAB": "Matrix Laboratory",
        "SBMT": "Small Body Mapping Tool",
        "Python": "To include SciPy, NumPyu, AstroPy, SpiceyPy",
        "IRAF": "Image Reduction and Analysis Facility",
        "DS9": "FITS Image Display",
        "GDAL": "Geospatial Data Abstraction Library",
        "GMT": "Generic Mapping Tools",
        "Other": "Any visualization software"
      }
    },
    "Modeling": {
      "definition": "Key modeling software",
      "permissible_values": {
        "GISS ROCKE-3D": "Java Mission-planning and Analysis for Remote Sensing",
        "GEODYN": "Integrated Software for Imagers and Spectrometers",
        "Melts": "Magmatic Equilibrium Liquidus Temperature Software for cosmochemistry",
        "COMSOL Multiphyics": "Simulating physical processes",
        "FLASH": "FLASH/ Athena/PLUTO",
        "iSALE": "Shock physics code for impact cratering, planetary interior",
        "HYDRA": "multi-material Eulerian code",
        "SPH": "Smoothed Particle Hydrodynamics",
        "CTH": "Collide, Track, Hydrodynamics",
        "LSDYNA": "Finite element analysis (FEA) code",
        "SPLAT": "SPectral Luminance and Temperature",
        "MYSTIC": "Radiative transfer modeling",
        "Other": "Any visualization software"
      }
    },
    "Orbital Mechanics & Mission Support": {
      "definition": "Software used for navigation or modeling",
      "permissible_values": {
        "GMAT": "General Mission Analysis Tool",
        "STK": "Satellite/System Tool Kit",
        "SPICE": "SPICE Toolkit from NAIF",
        "Orekit": "Orbital mechanics and space flight dynamics",
        "Simulink": "Add-on for MatLAB",
        "Celestia": "Astronomy, orbital visualization",
        "Rebound": "N-body simulations",
        "Mercury": "N-body code",
        "Swift": "N-body simulations",
        "Other": "Any visualization software"
      }
    },
    "Digital Terrain Modeling": {
      "definition": "Key modeling software",
      "permissible_values": {
        "SPC": "Sterophotoclinometry",
        "Stereo": "Photogrammetry",
        "Ames Stereo Pipeline": "Ames Pipeline",
        "SOCET Set": "SOCET Set",
        "Shape_From_Shading": "Shape from shading technique",
        "Shape_From_Modeling": "DTM generated from shape from motion technique",
        "Other": "Any visualization software"
      }
    },
    "Other": {
      "definition": "Any software not covered by other values"
    }
  }
};
